import globals from "globals";
import prettier from "eslint-plugin-prettier";
import eslintConfigPrettier from "eslint-config-prettier";
import eslintPluginReact from "eslint-plugin-react";
import eslintPluginReactRefresh from "eslint-plugin-react-refresh";
import eslintPluginJsxA11y from "eslint-plugin-jsx-a11y";

export default [
	{
		languageOptions: {
			sourceType: "module",
			globals: {
				...globals.browser,
			},
			parserOptions: {
				ecmaFeatures: {
					jsx: true,
				},
			},
		},
		plugins: {
			prettier: prettier,
			"jsx-a11y": eslintPluginJsxA11y,
			react: eslintPluginReact,
			"react-refresh": eslintPluginReactRefresh,
		},
		rules: {
			"react/jsx-uses-react": "error",
			"react/jsx-uses-vars": "error",
			"jsx-a11y/alt-text": "warn",
			"jsx-a11y/anchor-ambiguous-text": "warn",
			"jsx-a11y/anchor-has-content": "warn",
			"jsx-a11y/anchor-is-valid": "warn",
			"jsx-a11y/aria-activedescendant-has-tabindex": "warn",
			"jsx-a11y/aria-props": "warn",
			"jsx-a11y/aria-proptypes": "warn",
			"jsx-a11y/aria-role": "warn",
			"jsx-a11y/aria-unsupported-elements": "warn",
			"jsx-a11y/autocomplete-valid": "warn",
			"jsx-a11y/heading-has-content": "warn",
			"jsx-a11y/html-has-lang": "warn",
			"jsx-a11y/iframe-has-title": "warn",
			"jsx-a11y/img-redundant-alt": "warn",
			"jsx-a11y/interactive-supports-focus": "warn",
			"jsx-a11y/label-has-associated-control": "off",
			"jsx-a11y/lang": "warn",
			"jsx-a11y/media-has-caption": "off",
			"jsx-a11y/mouse-events-have-key-events": "warn",
			"jsx-a11y/no-access-key": "warn",
			"jsx-a11y/no-aria-hidden-on-focusable": "warn",
			"jsx-a11y/no-autofocus": "warn",
			"jsx-a11y/no-distracting-elements": "warn",
			"jsx-a11y/no-interactive-element-to-noninteractive-role": "warn",
			"jsx-a11y/no-noninteractive-element-interactions": "warn",
			"jsx-a11y/no-noninteractive-element-to-interactive-role": "warn",
			"jsx-a11y/no-noninteractive-tabindex": "warn",
			"jsx-a11y/no-redundant-roles": "warn",
			"jsx-a11y/role-has-required-aria-props": "warn",
			"jsx-a11y/role-supports-aria-props": "warn",
			"jsx-a11y/scope": "warn",
			"jsx-a11y/tabindex-no-positive": "warn",
			"react-refresh/only-export-components": "warn",
			"react/boolean-prop-naming": "warn",
			"react/button-has-type": "off",
			"react/forbid-dom-props": ["warn", { forbid: ["style"] }],
			"react/function-component-definition": [
				"warn",
				{
					namedComponents: "function-declaration",
					unnamedComponents: "arrow-function",
				},
			],
			"react/hook-use-state": "warn",
			"react/iframe-missing-sandbox": "warn",
			"react/jsx-boolean-value": ["warn", "never"],
			"react/jsx-child-element-spacing": "warn",
			"react/jsx-closing-bracket-location": ["warn", "tag-aligned"],
			"react/jsx-closing-tag-location": "warn",
			"react/jsx-equals-spacing": ["warn", "never"],
			"react/jsx-filename-extension": [
				"warn",
				{ extensions: [".jsx", ".js", ".tsx"] },
			],
			"react/jsx-first-prop-new-line": "warn",
			"react/jsx-fragments": "warn",
			"react/jsx-handler-names": [
				"warn",
				{
					eventHandlerPropPrefix: false,
				},
			],
			"react/jsx-key": "warn",
			"react/jsx-no-comment-textnodes": "warn",
			"react/jsx-no-constructed-context-values": "warn",
			"react/jsx-no-duplicate-props": "warn",
			"react/jsx-no-script-url": "warn",
			"react/jsx-no-target-blank": "warn",
			"react/jsx-no-undef": "warn",
			"react/jsx-no-useless-fragment": "warn",
			"react/jsx-pascal-case": "warn",
			"react/no-array-index-key": "off",
			"react/no-children-prop": "warn",
			"react/no-danger": "warn",
			"react/no-danger-with-children": "warn",
			"react/no-deprecated": "warn",
			"react/no-find-dom-node": "warn",
			"react/no-invalid-html-attribute": "warn",
			"react/no-multi-comp": ["warn", { ignoreStateless: true }],
			"react/no-namespace": "warn",
			"react/no-object-type-as-default-prop": "warn",
			"react/no-render-return-value": "warn",
			"react/no-string-refs": "warn",
			"react/no-this-in-sfc": "warn",
			"react/no-unescaped-entities": "warn",
			"react/no-unknown-property": "warn",
			"react/no-unstable-nested-components": "warn",
			"react/prefer-stateless-function": "warn",
			"react/prop-types": "off",
			"react/react-in-jsx-scope": "off",
			"react/self-closing-comp": "warn",
			"react/style-prop-object": "warn",
			"react/void-dom-elements-no-children": "warn",
		},
		settings: {
			react: {
				version: "18.2.0",
			},
		},
		files: ["**/*.jsx", "**/*.tsx"],
		ignores: ["./dist/assets/*.js"],
	},
	eslintConfigPrettier,
];
